version: '3.9'

services:
  web:
    build: .
    command: bash entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - static:/home/app/web/static
    env_file:
      - ./.env

  postgres:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/home/app/web/static
    depends_on:
      - web

volumes: 
  postgres_data:
  static: